<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Services/Detection/FinancialFraudPlatform.Detection.ML/FinancialFraudPlatform.Detection.ML.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" />
    <PackageReference Include="Microsoft.ML.FastTree" />
    <PackageReference Include="Microsoft.ML.OnnxConverter" />
  </ItemGroup>
</Project>
