<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../FinancialFraudPlatform.Core/FinancialFraudPlatform.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>
</Project>
